default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  min_messages: warning
  variables:
    statement_timeout: 15000 # ms or 15 seconds
    
development:
  <<: *default
  
test:
  <<: *default
  
testing:
  <<: *default
  
staging:
  <<: *default

production:
  <<: *default